# Jekyll (GitHub Pages) Configuration

base_url: https://cyhi.lexi.se
assets_base_url: ""
google_analytics_id: UA-XXXXXXXX-X
prevent_crawling: true
permalink: /:path
collections:
  articles:
    output: true
    permalink: /artiklar/:path
exclude:
  - hooks
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
