base_url: http://atea-cyhi-staging.s3-website.eu-north-1.amazonaws.com
assets_base_url: http://atea-cyhi-staging.s3-website.eu-north-1.amazonaws.com
google_analytics_id: ""
prevent_crawling: true
permalink: /:path
collections:
  articles:
    output: true
    permalink: /artiklar/:path
  videos:
    output: true
    permalink: /hthi/:path
