# Jekyll (GitHub Pages) Configuration

base_url: https://cyhi.kwdstudio.se
assets_base_url: ""
google_analytics_id:
prevent_crawling: false
permalink: /:path
collections:
  videos:
    output: true
    permalink: /hthi/:path
  articles:
    output: true
    permalink: /artiklar/:path
exclude:
  - hooks
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
